### ISSUE TITLE
MSI Uninstall doesn't work because there is not SPACE between /x and $InstallGuid

### ISSUE THREAD

**Issue by Antebios** [vercellone/vsts-btdf-tasks#1]
Before:
$args = [string[]]@(
    "/x$InstallGuid"
    "/qn"

Needs to be After:
$args = [string[]]@(
    "/x $InstallGuid"
    "/qn"

**Comment by vercellone** [comment]
Fairly certain it works both ways for my purposes.  But, I've added the space to accommodate.
